### ISSUE TITLE
Eliminate `strides = strides / self.img_size` in the `Detect` Module

### ISSUE THREAD

**Issue by ambitious-octopus** [ambitious-octopus/model_optimization#3]
The sony-yolov8 `Detect` [module](https://github.com/sony/model_optimization/blob/8461a41fa8b6b57ce422fdd5f7301e9a9c8a1b20/tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py#L245) currently includes the line `strides = strides / self.img_size` which has been identified as problematic for two reasons:
1. The variable `strides` is not present in our package.
2. The operation results in incorrect outcomes during inference.

However, if this line might be necessary for the quantization process. If possible, we should remove this line from the `Detect` module. If it is indeed required for quantization, we can consider moving it into the postprocessing step instead of injecting it into Detect Head.

**Comment by Idan-BenAmi** [comment]
Hi @ambitious-octopus,

This modification was mostly done in order to mitigate the problem that described in: https://github.com/ambitious-octopus/model_optimization/issues/1
The 2 issues are related. 
Normalizing the coordinates of the bounding boxes to the range of [0, 1], will align it with the value range of the scores [0,1] and can ease the output tensor quantization.
If you decide to keep the modification in https://github.com/ambitious-octopus/model_optimization/issues/1, we think this modification can be removed.

Thanks
Idan

**Comment by ambitious-octopus** [comment]
Hey @Idan-BenAmi,  @Laughing-q  has correctly separated the two parts in this [PR](https://github.com/ultralytics/ultralytics/pull/14878). Unfortunately, when testing the model without this stride normalization, we notice a strong degradation in performance. Can you help us understand the problem?

**Comment by Idan-BenAmi** [comment]
Hi @ambitious-octopus, @Laughing-q ,
So the stride normalization affects significantly on the model's output and should be corrected in the evaluation process correspondingly. By the way, how do you test the model's performance? (I mean, using Ultralytics evaluator or ours evaluator code?).  if you use our evaluator, I can send you the required modification in the evaluation code.

I will also try it myself to make sure there’s no significant drop.
Idan

**Comment by ambitious-octopus** [comment]
Hey @Idan-BenAmi We are using your evaluator. This is the code:
https://github.com/ambitious-octopus/model_optimization/blob/dbf434207e3aec5a3b9ef16c3740701a4cb150e8/ultralytics-exports/vanilla-yolo.py#L1-L153

**Comment by Idan-BenAmi** [comment]
Hi @ambitious-octopus, 
Thanks, just wanted to make sure.
I tried it myself and there is indeed a small modification to make in the evaluation code.
Please follow this [PR](https://github.com/sony/model_optimization/pull/1175/files) for the required changes.

In addition, after removing the stride normalization from the model, please modify the vanilla-yolo.py, line 131:
```python
output_resize = {'shape': (INPUT_RESOLUTION, INPUT_RESOLUTION), 'aspect_ratio_preservation': True, 'normalized_coords': False} 
```
Let mw know if it works for you.

Idan

**Comment by Laughing-q** [comment]
> Hi @ambitious-octopus, Thanks, just wanted to make sure. I tried it myself and there is indeed a small modification to make in the evaluation code. Please follow this [PR](https://github.com/sony/model_optimization/pull/1175/files) for the required changes.
> 
> In addition, after removing the stride normalization from the model, please modify the vanilla-yolo.py, line 131:
> 
> ```python
> output_resize = {'shape': (INPUT_RESOLUTION, INPUT_RESOLUTION), 'aspect_ratio_preservation': True, 'normalized_coords': False} 
> ```
> 
> Let mw know if it works for you.
> 
> Idan

@Idan-BenAmi @ambitious-octopus Hey guys I tested with the changes and it works properly after I removed the `stride / 640`. Thanks!
